name: publish
env:
  CI: true
on:
  push:
    branches:
      - main
    tags:
      - '!*'
jobs:
  release:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com'
      - name: install
        run: npm install
      - name: test
        run: npm test
      - name: Npm github registry configuration
        run: |
          echo "npm config set \"//npm.pkg.github.com/:_authToken\" $GU_PACKAGES_GITHUB_TOKEN" && npm config set "//npm.pkg.github.com/:_authToken" $GU_PACKAGES_GITHUB_TOKEN
        env:
          GU_PACKAGES_GITHUB_TOKEN: ${{ secrets.GU_PACKAGES_GITHUB_TOKEN }}
      # Publish to npm if this version is not published
      - name: Publish
        run: |
          npx can-npm-publish packages/gu-animator --verbose && npm publish packages/gu-animator --access restricted || echo "Does not publish"
        env:
          GU_PACKAGES_GITHUB_TOKEN: ${{ secrets.GU_PACKAGES_GITHUB_TOKEN }}
      # Push tag to GitHub if the version's tag is not tagged
      - name: package-version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - name: package-version-to-git-tag
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GU_PACKAGES_GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ env.PACKAGE_VERSION }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: 'v'
